---
- hosts: all
  become: true
  gather_facts: false
  tasks:
  - 
    yum:
     name: ['git', 'wget', 'tree' ]
     state: present
     update_cache: yes
    name: "Install git,wget,tree on all nodes" 
    