---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install httpd on all nodes
    yum:
       name: httpd
       state: latest
  
  - name: Start the service
    service:
         name: httpd
         state: latest    