---
- hosts: all
  become: yes
  tasks: 
  - name: Install git on all nodes
    yum:
       name: git
       state: present
       update_cache: yes


  - name: Install wget
    yum:
       name: wget
       state: present


  - name: Install tree
    yum:
      name: tree
      state: present    
